### PR TITLE
Email support

### PR DESCRIPTION
**Pull request by Josue-T**
## Problem

- No support for sending email

## Solution

- Add support to send email from coin with yunohost email config

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Josue-T** [comment]
!testme

**Comment by Josue-T** [comment]
Note that the CI fail because a regression of #33

**Comment by Josue-T** [comment]
!testme

**Comment by Josue-T** [comment]
!testme

**Comment by Josue-T** [comment]
Hello, will merge it tomorrow, I nobody disagree.

**Review by alexAubin — APPROVED** [review]

**Comment by ShaAlexander** [comment]
Why do i keep getting unnecessary notifications form a lot of yh forum and now even github? Why?!

**Pull request merged**
